server:
  port: 9995

spring:
  application:
    name: file
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/geek_space
    username: root
    password: 695641275abcd

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000