server:
  port: 9991

spring:
  application:
      name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: 695641275abcd
    gateway:
      server:
        webflux:
           routes:
           - id: auth
             uri: lb://auth
             predicates:
               - Path=/geek/auth/**
           - id: user
             uri: lb://user
             predicates:
               - Path=/geek/user/**


jwt:
  secret_key: secret
