server:
  port: 9990

spring:
  application:
      name: auth
  cloud:
    nacos:
        discovery:
            server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/geek_space
    username: root
    password: 695641275abcd

mybatis-plus:
  global-config:
      db-config:
        logic-delete-field: status
        logic-delete-value: 0
        logic-not-delete-value: 1

jwt:
  secret_key: secret
